### ISSUE TITLE
How do I use this script? 

### ISSUE THREAD

**Issue by ivanquirino** [ultralytics/COCO2YOLO#1]
I have a coco.json file but when I run this script I've got the following error:
```
Traceback (most recent call last):
  File "./run.py", line 88, in <module>
    main(name, file)
  File "./run.py", line 60, in main
    with open('out/labels/' + label_name, 'a') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'out/labels/IMG_https://storage.googleapis.com/labelbox-193903.appspot.com/cjvzre25678v10804t8epwim4%2F501af721-032d-33d3-e4b5-cc584ff45244-769a3159-1ecf-4f3e-aa8f-e09f0bde6014_LA.txt'
```

**Comment by glenn-jocher** [comment]
@ivanquirino this script can be used to import JSON files from other formats into the YOLO format used for training darknet or ultralytics/yolov3.

**Comment by getcontrol** [comment]
What is the EXACT command to execute this script?

- I have installed the dependancies in python3 venv

- I have my LabelBox JSON file in the root directory /Users/getcontrol/projects/JSON2YOLO/export-2019-11-18T18_30_26.769Z.json

I  enter in terminal: 

> python run.py export-2019-11-18T18_30_26.769Z.json

also try simply 

> python run.py

Output = 
```
Files and Shapes: 0it [00:00, ?it/s]
Annotations: 0it [00:00, ?it/s]
Done. Output saved to /Users/getcontrol/projects/JSON2YOLO/../out/`
```


All of the files and directories in out/ are empty.
![Screenshot 2019-11-18 11 06 13](https://user-images.githubusercontent.com/9941190/69081745-80278d00-09f3-11ea-9879-b71f5a8205ea.png)

**Comment by glenn-jocher** [comment]
@ivanquirino you can modify this section to specify labelbox format and to point to your labelbox json:

https://github.com/ultralytics/JSON2YOLO/blob/898f174547b6485d132fa903427d316f33e9d721/run.py#L302-L308

**Comment by joehoeller** [comment]
Same issue with this one, lack of docs. I have COCO annotations in JSON format and not sure which one I can use to format 'COCO JSON'  into 'Darknet .txt format'.

**Comment by joehoeller** [comment]
For example, my COCO JSON Annotations look like this, in which I have a unique JSON file for every image:
```
{
    "annotation": [
        {
            "area": 7350,
            "bbox": [
                396,
                200,
                147,
                50
            ],
            "category_id": "3",
            "id": 1,
            "image_id": 2,
            "iscrowd": 0,
            "segmentation": [
                [
                    396,
                    200,
                    396,
                    250,
                    543,
                    250,
                    543,
                    200
                ]
            ]
        } 
]
```
I need to know how to use the ```run.py``` file to make .txt files for Darknet, that look like this:
```
3 0.497327 0.511852 0.948637 0.952609 
3 0.240637 0.217617 0.475398 0.424859 
```

**Comment by glenn-jocher** [comment]
@joehoeller the repo only offers export from a limited number of JSON labelling providers below. Since each JSON format is different, we have to write custom functions for each format. We don't have a COCO JSON export function yet.

- Labelbox https://labelbox.com/
- Infolks https://infolks.info/
- VoTT https://github.com/microsoft/VoTT

**Comment by joehoeller** [comment]
Can you add me to the project so I can contrib the following:

1. COCO JSON -> Darknet/YOLO .txt format
2. Write new or re-write better tutorials/docs
3. Composable metrics for any CNN arch used

**Comment by glenn-jocher** [comment]
@joehoeller may try this script: https://github.com/AlexeyAB/darknet/issues/3772#issuecomment-559242998

Yeah I can add you on. I forgot how to do that! Let me check.

**Comment by joehoeller** [comment]
@glenn-jocher I guess no one had a working script that would automate COCO JSON -> Darknet. I made one :) let me know when I’m added to repo and I’ll post as pull request.

**Comment by SteelMinh** [comment]
@joehoeller can you show me your script that convert the JSON to Darknet?

**Comment by joehoeller** [comment]
> @joehoeller can you show me your script that convert the JSON to Darknet?

It may have some bugs, so let me know, and I'll fix. Its basically a version 0.5 right now: https://github.com/joehoeller/Dark-Chocolate,

**Comment by joehoeller** [comment]
> @joehoeller may try this script: [AlexeyAB/darknet#3772 (comment)](https://github.com/AlexeyAB/darknet/issues/3772#issuecomment-559242998)
> 
> Yeah I can add you on. I forgot how to do that! Let me check.

not added yet

**Comment by Goldenstarc** [comment]
finally, How to use this with VoTT JSON ?
is there any instruction ?

**Comment by duyao-art** [comment]
@glenn-jocher  Hello! Thank you for your advice recently. 

I have a question. Now I want to retrain the yolov3 based on my built dateset. I am wondering if there are some requirements about the image size? Should the image data has the same size? Does the same size will make the train and detection accuracy better? I know in your Yolo project, there are several codes to transform the input image size to the standard 416*416 or other unit 32 image size. I just wonder if it is needed to revise the size of my collected image size, because the sizes are different. Also, if it is also necessary that the image format must be .jpg format, can not be .png or other format?

I would be appreciated if you could reply to  me in your free time.

**Comment by glenn-jocher** [comment]
@duyao-art @Goldenstarc these are mostly internal tools we use for some client conversions that we've uploaded to github for version control purposes, hence the lack of documentation.

**Comment by duyao-art** [comment]
@glenn-jocher  OK. Thank you again for your kind reply.

**Comment by Goldenstarc** [comment]
It’s a perfect tool.  I wish you publish its instructions manual publicly.

**Comment by khandriod** [comment]
@Hamid-Najafi how did you use this tool? Could you please help me with it get started?

**Comment by glenn-jocher** [comment]
@Hamid-Najafi thanks for your interest! Feel free to ask any specific questions you may have about using the tool. I'm here to help!

**Comment by Mary14-design** [comment]
Coco dataset contains multiple json files, not only one. How to convert each one?

**Comment by glenn-jocher** [comment]
@Mary14-design hello! 😊 To convert multiple COCO JSON files to the format expected by our tool, you can use a simple loop in your script. Here's a basic example:

```python
import os

json_files = ['path/to/your/first.json', 'path/to/your/second.json']  # Add your JSON file paths here
for json_file in json_files:
    # Your conversion function here, e.g.,
    convert_coco_json(json_file, output_dir='desired/output/path')
```

Just replace `convert_coco_json` with the actual function you're using for conversion, and ensure `json_files` contains the paths to all your COCO JSON files. This way, each file will be processed in turn. If you have any further questions, feel free to ask! 🚀

**Comment by DishantMewada** [comment]
Step 1: First install requirements with pip install -r requirements.txt
Step 2: I placed my json files in "data" folder and changed the "general_json2yolo.py" as follows
`if __name__ == "__main__":
    source = "COCO"

    if source == "COCO":
        convert_coco_json(
            "./data/",  # directory with *.json
            use_segments=False,
            cls91to80=True,
        )
`
Step 3: run it with "python general_json2yolo.py"
It will create new_dir/labels/name_of_the_json_file/*.txt

**Comment by furycurry** [comment]
Hello @pderrenger,

May I ask for the directory structure which is required to convert JSON to yolo format?

**Comment by pderrenger** [comment]
Hello @furycurry,  

The required directory structure typically involves placing your JSON files in a directory (e.g., `./data/`) and specifying this path in the script. The converter will process all JSON files in the directory and output the YOLO labels in a dedicated `labels/` folder. Let me know if you encounter any issues!

**Comment by glenn-jocher** [comment]
Thanks everyone who added context here over the years. PR #11 by @GiorgioSgl has now been rescued and merged, adding CLI arguments for the legacy standalone script, and the README also points to the maintained ultralytics.data.converter.convert_coco() API. For legacy COCO usage: python general_json2yolo.py --source COCO --json-dir path/to/annotations --use-segments.
